### PR TITLE
added flexible mode to ignore env var issues

### PR DESCRIPTION
**Pull request by cleveryifan**
This is not very robust but it enables the run despite the env variables. Happy to take in suggestions to make this more robust!

### CODE REVIEW

**Comment by dfuentes** [comment]
Please don't do this.  We just got done making the opposite of this change (ensuring that aviator will not run with missing environment variables)

**Comment by cleveryifan** [comment]
OK! Sorry didn't know about the big picture!

On Mon, Mar 9, 2015 at 10:18 PM, Daniel Fuentes <notifications@github.com>
wrote:

> Please don't do this. We just got done making the opposite of this change
> (ensuring that aviator will not run with missing environment variables)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Clever/aviator/pull/28#issuecomment-77997440>.
>



-- 
Yifan

**Comment by agclever** [comment]
@dfuentes This is not the complete opposite of the previous change. A lot of environment variables are not strictly needed for bringing up local instances. Right now people set them to arbitrary values like `foo`, `bar`. The motivation here is to allow marking environment variables as optional for these cases.

**Comment by dfuentes** [comment]
@agclever This change as implemented is the opposite, what you propose is not.

In my opinion, we should not have a config that says required, but not actually have those values be requirements.

An optional config is a possibility, but I also think that that is harmful in the long run.  What we end up with is some people running with some environment variables set, and some not, making comparisons between setups from two different people more difficult.  I think it reintroduces the "works for me" problem, and in general makes reproducibility harder.

**Pull request closed without merging**
