### PR TITLE
Allow values to contain multiple env vars at arbitrary indices

### PR DESCRIPTION
**Pull request by agclever**
Right now, aviator values containing environment variables can be of the format `$ENV_VAR`. This change allows an multiple env vars to be present in the values which maybe interspersed at any location in the string. For example `foo$ENV1/$ENV2` is now a valid aviator value.

Tested: unit tests.

### CODE REVIEW

**Comment by agclever** [comment]
cc: @templaedhel

**Comment by dfuentes** [comment]
:+1: Really like this change

**Comment by rgarcia** [comment]
The `requires` section could really use some documentation. If I understand it correctly, the `requires` section can now take in values that are either environment variables, e.g.
```yaml
MONGO_URL: "MONGO_URL"
```
or published values from other services, e.g.
```yaml
MONGO_URL: "il_mongodb.conn_string"
```
or a string constructed from existing environment variables
```yaml
MONGO_URL: "mongodb://$MONGO_HOST/clever"
```
Personally I'm starting to get a little confused... We should consider removing support for the first format now that this PR has been merged.

Also, I predict that one day someone is going to put 
```yaml
MONGO_URL: "mongodb://127.0.0.1/$MONGO_DB"
```
and confuse the logic here into looking up a service named `mongodb://127`. But we can cross that bridge when we come to it.

**Comment by dfuentes** [comment]
I agree its a bit confusing.  There are a few ways  you could go about fixing it:

1)  You could have two sections, one for interpolation variables (environment variables, values pulled from dependencies), and a section for string interpolation).  This could also serve to make dependencies not rely solely on environment variable need.
2)  You could have a special syntax for values pulled from other services ($$service.variable for example)

I'd be curious to hear your thoughts on how we could make it more clear/usable.

**Pull request merged**
