### PR TITLE
fix pingpong example

### LINKED ISSUE #29: ping-pong example broken
```
Clevers-MacBook-Pro:pingpong rgarcia$ cat server/aviator.yml 
pong:
  setups:
    default:
      publish:
        pong.server: "localhost:8080"
      cmd: ./server.sh
Clevers-MacBook-Pro:pingpong rgarcia$ cat client/aviator.yml 
ping:
  setups:
    default:
      cmd: ./client.sh
  requires:
    SERVER: pong.server
Clevers-MacBook-Pro:pingpong rgarcia$ aviator ping
Error: found service 'pong', but it does not publish key 'server'
```

It appears at some point we introduced auto-namespacing of published values. The example can be fixed by changing `pong.server` to just `server`.

### PR DESCRIPTION
**Pull request by rgarcia**
values are now automatically published within the service namespace

fixes #29

### CODE REVIEW

**Comment by nathanleiby** [comment]
(lgtm)

**Comment by nathanleiby** [comment]
Would be nice to add running the example with aviator to the automated test cases.

**Comment by dfuentes** [comment]
lgtm

**Comment by rgarcia** [comment]
@nathanleiby yeah, perhaps via http://golang.org/pkg/testing/#hdr-Examples. For another day...

**Pull request merged**
