### PR TITLE
`make install` will install aviator for macs

### PR DESCRIPTION
**Pull request by MaerF0x0**
Just wanted an easy way to install .

Please merge and delete branch (and whatever else) if LGTM.

### CODE REVIEW

**Comment by dfuentes** [comment]
seems strange to add an install that only works on mac.

**Comment by clever-drone** [comment]
it is, but I dont have an env to test otherwise, they could iterate if they
want their own.

--
Mike Graf
Clever
m | 415-425-5880
http://engineering.clever.com

**Comment by dfuentes** [comment]
Who is `they`?  This seems like a solution specific to your setup.

**Comment by clever-drone** [comment]
This should work for any mac, please help me understand if/where I'm wrong.

--
Mike Graf
Clever
m | 415-425-5880
http://engineering.clever.com

**Comment by dfuentes** [comment]
At least make it consistent with where salt-dev-env installs (/usr/local/bin).  I think it's also more common to not use sudo inside the makefile (and instead invoke make with sudo)?

**Comment by dfuentes** [comment]
I think we should wait until Rafs pr is merged which makes go build properly build in the root dir, then we can copy that file and it will be cross platform (because it will be whatever platform you built on)

**Comment by dfuentes** [comment]
@MaerF0x0 how do you feel about this, does install, keeps it cross platform?

**Comment by MaerF0x0** [comment]
:100:  Ty!
[LGTM](http://www.lgtm.in/i/A8jr413Pp)

**Pull request merged**
