### PR TITLE
drone.yml: install toolchain before compiling release

### PR DESCRIPTION
**Pull request by rgarcia**

### CODE REVIEW

**Comment by nathanleiby** [comment]
Do you prefer this logic in drone over Makefile? 

- one upside to Makefile is that `make release` would work locally
- downside to Makefile is that is it would compile for more than one architecture even if that's not needed. 

I notice we aren't yet doing this for other repos yet. Similar change needed there?

- https://github.com/Clever/clever-cli/blob/master/.drone.yml#L17-20
- https://github.com/Clever/moredis/blob/master/.drone.yml#L17-20

**Comment by rgarcia** [comment]
That's a good point--I will experiment with that.

**Comment by rgarcia** [comment]
@nathanleiby updated to do this in the makefile!

**Comment by nathanleiby** [comment]
nice- I like this Makefile approach.

lgtm

**Pull request merged**
